name: lenet5_CIFAR10_12x16
model: LeNet5
gpu_ids: [0]
class_num: 10

in_chans: 1
img_size: [16, 16]
class_num: 10

### datasets
datasets:
  train:
    name: CIFAR10
    dataroot: ../../datasets/CLSDatasets/CIFAR10
    
    is_pretrain: true  # whether to process the preprocess
    src_img_size: [28, 28, 1]
    fake_img_size: [12, 16, 1]

    workers_per_gpu: 0
    imgs_per_gpu: 256
  
  val:
    name: CIFAR10
    dataroot: ../../datasets/CLSDatasets/CIFAR10

    is_pretrain: true  # whether to process the preprocess
    src_img_size: [28, 28, 1]
    fake_img_size: [12, 16, 1]
    
    imgs_per_gpu: 32

### training
train:
  manual_seed: 1234

  optimizer:
    type: Adam
    lr: !!float 1e-3

  niter: 64000

  scheduler:
    type: MultiStepRestartLR
    milestones: [32000, 48000]
    gamma: 0.5
  
  val_freq: !!float 2e3

logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e3
